repos:
-   repo: https://github.com/pycqa/flake8
    rev: '6.1.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        exclude: 'migrations|docs|examples|vendor|venv|management|static'
